var searchData=
[
  ['gamma_0',['Gamma',['../class_numerics_1_1_mathematics_1_1_special_functions_1_1_gamma.html',1,'Numerics::Mathematics::SpecialFunctions']]],
  ['gammadistribution_1',['GammaDistribution',['../class_numerics_1_1_distributions_1_1_gamma_distribution.html',1,'Numerics::Distributions']]],
  ['gaussianmixturemodel_2',['GaussianMixtureModel',['../class_numerics_1_1_machine_learning_1_1_gaussian_mixture_model.html',1,'Numerics::MachineLearning']]],
  ['gaussjordanelimination_3',['GaussJordanElimination',['../class_numerics_1_1_mathematics_1_1_linear_algebra_1_1_gauss_jordan_elimination.html',1,'Numerics::Mathematics::LinearAlgebra']]],
  ['generalizedbeta_4',['GeneralizedBeta',['../class_numerics_1_1_distributions_1_1_generalized_beta.html',1,'Numerics::Distributions']]],
  ['generalizedextremevalue_5',['GeneralizedExtremeValue',['../class_numerics_1_1_distributions_1_1_generalized_extreme_value.html',1,'Numerics::Distributions']]],
  ['generalizedlogistic_6',['GeneralizedLogistic',['../class_numerics_1_1_distributions_1_1_generalized_logistic.html',1,'Numerics::Distributions']]],
  ['generalizednormal_7',['GeneralizedNormal',['../class_numerics_1_1_distributions_1_1_generalized_normal.html',1,'Numerics::Distributions']]],
  ['generalizedpareto_8',['GeneralizedPareto',['../class_numerics_1_1_distributions_1_1_generalized_pareto.html',1,'Numerics::Distributions']]],
  ['geometric_9',['Geometric',['../class_numerics_1_1_distributions_1_1_geometric.html',1,'Numerics::Distributions']]],
  ['gibbs_10',['Gibbs',['../class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_gibbs.html',1,'Numerics::Sampling::MCMC']]],
  ['goldensection_11',['GoldenSection',['../class_numerics_1_1_mathematics_1_1_optimization_1_1_golden_section.html',1,'Numerics::Mathematics::Optimization']]],
  ['goodnessoffit_12',['GoodnessOfFit',['../class_numerics_1_1_data_1_1_statistics_1_1_goodness_of_fit.html',1,'Numerics::Data::Statistics']]],
  ['gradientdescent_13',['GradientDescent',['../class_numerics_1_1_mathematics_1_1_optimization_1_1_gradient_descent.html',1,'Numerics::Mathematics::Optimization']]],
  ['gumbel_14',['Gumbel',['../class_numerics_1_1_distributions_1_1_gumbel.html',1,'Numerics::Distributions']]],
  ['gumbelcopula_15',['GumbelCopula',['../class_numerics_1_1_distributions_1_1_copulas_1_1_gumbel_copula.html',1,'Numerics::Distributions::Copulas']]]
];
