var hierarchy =
[
    [ "Numerics.Data.Statistics.Autocorrelation", "class_numerics_1_1_data_1_1_statistics_1_1_autocorrelation.html", null ],
    [ "Numerics.Mathematics.SpecialFunctions.Beta", "class_numerics_1_1_mathematics_1_1_special_functions_1_1_beta.html", null ],
    [ "Numerics.Data.Bilinear", "class_numerics_1_1_data_1_1_bilinear.html", null ],
    [ "Numerics.Mathematics.RootFinding.Bisection", "class_numerics_1_1_mathematics_1_1_root_finding_1_1_bisection.html", null ],
    [ "Numerics.Distributions.Copulas.BivariateCopulaEstimation", "class_numerics_1_1_distributions_1_1_copulas_1_1_bivariate_copula_estimation.html", null ],
    [ "Numerics.Distributions.BootstrapAnalysis", "class_numerics_1_1_distributions_1_1_bootstrap_analysis.html", null ],
    [ "Numerics.Data.Statistics.BoxCox", "class_numerics_1_1_data_1_1_statistics_1_1_box_cox.html", null ],
    [ "Numerics.Mathematics.RootFinding.Brent", "class_numerics_1_1_mathematics_1_1_root_finding_1_1_brent.html", null ],
    [ "Numerics.Mathematics.LinearAlgebra.CholeskyDecomposition", "class_numerics_1_1_mathematics_1_1_linear_algebra_1_1_cholesky_decomposition.html", null ],
    [ "Numerics.Data.Statistics.Correlation", "class_numerics_1_1_data_1_1_statistics_1_1_correlation.html", null ],
    [ "Numerics.Mathematics.SpecialFunctions.Debye", "class_numerics_1_1_mathematics_1_1_special_functions_1_1_debye.html", null ],
    [ "Numerics.MachineLearning.DecisionNode", "class_numerics_1_1_machine_learning_1_1_decision_node.html", null ],
    [ "Numerics.MachineLearning.DecisionTree", "class_numerics_1_1_machine_learning_1_1_decision_tree.html", null ],
    [ "Numerics.Mathematics.SpecialFunctions.Erf", "class_numerics_1_1_mathematics_1_1_special_functions_1_1_erf.html", null ],
    [ "Numerics.Mathematics.SpecialFunctions.Evaluate", "class_numerics_1_1_mathematics_1_1_special_functions_1_1_evaluate.html", null ],
    [ "Numerics.ExtensionMethods", "class_numerics_1_1_extension_methods.html", null ],
    [ "Numerics.Mathematics.SpecialFunctions.Factorial", "class_numerics_1_1_mathematics_1_1_special_functions_1_1_factorial.html", null ],
    [ "Numerics.Mathematics.Fourier", "class_numerics_1_1_mathematics_1_1_fourier.html", null ],
    [ "Numerics.Mathematics.SpecialFunctions.Gamma", "class_numerics_1_1_mathematics_1_1_special_functions_1_1_gamma.html", null ],
    [ "Numerics.MachineLearning.GaussianMixtureModel", "class_numerics_1_1_machine_learning_1_1_gaussian_mixture_model.html", null ],
    [ "Numerics.Mathematics.LinearAlgebra.GaussJordanElimination", "class_numerics_1_1_mathematics_1_1_linear_algebra_1_1_gauss_jordan_elimination.html", null ],
    [ "Numerics.Data.Statistics.GoodnessOfFit", "class_numerics_1_1_data_1_1_statistics_1_1_goodness_of_fit.html", null ],
    [ "Numerics.Data.Statistics.Histogram", "class_numerics_1_1_data_1_1_statistics_1_1_histogram.html", null ],
    [ "Numerics.Data.Statistics.HypothesisTests", "class_numerics_1_1_data_1_1_statistics_1_1_hypothesis_tests.html", null ],
    [ "Numerics.Distributions.Copulas.IArchimedeanCopula", "interface_numerics_1_1_distributions_1_1_copulas_1_1_i_archimedean_copula.html", [
      [ "Numerics.Distributions.Copulas.ArchimedeanCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_archimedean_copula.html", [
        [ "Numerics.Distributions.Copulas.AMHCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_a_m_h_copula.html", null ],
        [ "Numerics.Distributions.Copulas.ClaytonCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_clayton_copula.html", null ],
        [ "Numerics.Distributions.Copulas.FrankCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_frank_copula.html", null ],
        [ "Numerics.Distributions.Copulas.GumbelCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_gumbel_copula.html", null ],
        [ "Numerics.Distributions.Copulas.JoeCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_joe_copula.html", null ]
      ] ]
    ] ],
    [ "ICloneable", null, [
      [ "Numerics.Data.Statistics.Histogram.Bin", "class_numerics_1_1_data_1_1_statistics_1_1_histogram_1_1_bin.html", null ],
      [ "Numerics.Sampling.StratificationBin", "class_numerics_1_1_sampling_1_1_stratification_bin.html", null ]
    ] ],
    [ "IComparable", null, [
      [ "Numerics.Data.Statistics.Histogram.Bin", "class_numerics_1_1_data_1_1_statistics_1_1_histogram_1_1_bin.html", null ],
      [ "Numerics.Sampling.StratificationBin", "class_numerics_1_1_sampling_1_1_stratification_bin.html", null ]
    ] ],
    [ "Numerics.Mathematics.Optimization.IConstraint", "interface_numerics_1_1_mathematics_1_1_optimization_1_1_i_constraint.html", [
      [ "Numerics.Mathematics.Optimization.Constraint", "class_numerics_1_1_mathematics_1_1_optimization_1_1_constraint.html", null ]
    ] ],
    [ "Numerics.Distributions.IDistribution", "interface_numerics_1_1_distributions_1_1_i_distribution.html", [
      [ "Numerics.Distributions.Copulas.IBivariateCopula", "interface_numerics_1_1_distributions_1_1_copulas_1_1_i_bivariate_copula.html", [
        [ "Numerics.Distributions.Copulas.BivariateCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_bivariate_copula.html", [
          [ "Numerics.Distributions.Copulas.ArchimedeanCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_archimedean_copula.html", null ],
          [ "Numerics.Distributions.Copulas.NormalCopula", "class_numerics_1_1_distributions_1_1_copulas_1_1_normal_copula.html", null ]
        ] ]
      ] ],
      [ "Numerics.Distributions.IMultivariateDistribution", "interface_numerics_1_1_distributions_1_1_i_multivariate_distribution.html", [
        [ "Numerics.Distributions.MultivariateDistribution", "class_numerics_1_1_distributions_1_1_multivariate_distribution.html", [
          [ "Numerics.Distributions.BivariateEmpirical", "class_numerics_1_1_distributions_1_1_bivariate_empirical.html", null ],
          [ "Numerics.Distributions.MultivariateNormal", "class_numerics_1_1_distributions_1_1_multivariate_normal.html", null ]
        ] ]
      ] ],
      [ "Numerics.Distributions.IUnivariateDistribution", "interface_numerics_1_1_distributions_1_1_i_univariate_distribution.html", [
        [ "Numerics.Distributions.IBootstrappable", "interface_numerics_1_1_distributions_1_1_i_bootstrappable.html", [
          [ "Numerics.Distributions.CompetingRisks", "class_numerics_1_1_distributions_1_1_competing_risks.html", null ],
          [ "Numerics.Distributions.EmpiricalDistribution", "class_numerics_1_1_distributions_1_1_empirical_distribution.html", null ],
          [ "Numerics.Distributions.Exponential", "class_numerics_1_1_distributions_1_1_exponential.html", null ],
          [ "Numerics.Distributions.GammaDistribution", "class_numerics_1_1_distributions_1_1_gamma_distribution.html", null ],
          [ "Numerics.Distributions.GeneralizedExtremeValue", "class_numerics_1_1_distributions_1_1_generalized_extreme_value.html", null ],
          [ "Numerics.Distributions.GeneralizedLogistic", "class_numerics_1_1_distributions_1_1_generalized_logistic.html", null ],
          [ "Numerics.Distributions.GeneralizedNormal", "class_numerics_1_1_distributions_1_1_generalized_normal.html", null ],
          [ "Numerics.Distributions.GeneralizedPareto", "class_numerics_1_1_distributions_1_1_generalized_pareto.html", null ],
          [ "Numerics.Distributions.Gumbel", "class_numerics_1_1_distributions_1_1_gumbel.html", null ],
          [ "Numerics.Distributions.KappaFour", "class_numerics_1_1_distributions_1_1_kappa_four.html", null ],
          [ "Numerics.Distributions.KernelDensity", "class_numerics_1_1_distributions_1_1_kernel_density.html", null ],
          [ "Numerics.Distributions.LnNormal", "class_numerics_1_1_distributions_1_1_ln_normal.html", null ],
          [ "Numerics.Distributions.LogNormal", "class_numerics_1_1_distributions_1_1_log_normal.html", null ],
          [ "Numerics.Distributions.LogPearsonTypeIII", "class_numerics_1_1_distributions_1_1_log_pearson_type_i_i_i.html", null ],
          [ "Numerics.Distributions.Logistic", "class_numerics_1_1_distributions_1_1_logistic.html", null ],
          [ "Numerics.Distributions.Mixture", "class_numerics_1_1_distributions_1_1_mixture.html", null ],
          [ "Numerics.Distributions.Normal", "class_numerics_1_1_distributions_1_1_normal.html", null ],
          [ "Numerics.Distributions.PearsonTypeIII", "class_numerics_1_1_distributions_1_1_pearson_type_i_i_i.html", null ],
          [ "Numerics.Distributions.Pert", "class_numerics_1_1_distributions_1_1_pert.html", null ],
          [ "Numerics.Distributions.Triangular", "class_numerics_1_1_distributions_1_1_triangular.html", null ],
          [ "Numerics.Distributions.Weibull", "class_numerics_1_1_distributions_1_1_weibull.html", null ]
        ] ],
        [ "Numerics.Distributions.UnivariateDistributionBase", "class_numerics_1_1_distributions_1_1_univariate_distribution_base.html", [
          [ "Numerics.Distributions.Bernoulli", "class_numerics_1_1_distributions_1_1_bernoulli.html", null ],
          [ "Numerics.Distributions.BetaDistribution", "class_numerics_1_1_distributions_1_1_beta_distribution.html", null ],
          [ "Numerics.Distributions.Binomial", "class_numerics_1_1_distributions_1_1_binomial.html", null ],
          [ "Numerics.Distributions.Cauchy", "class_numerics_1_1_distributions_1_1_cauchy.html", null ],
          [ "Numerics.Distributions.ChiSquared", "class_numerics_1_1_distributions_1_1_chi_squared.html", null ],
          [ "Numerics.Distributions.CompetingRisks", "class_numerics_1_1_distributions_1_1_competing_risks.html", null ],
          [ "Numerics.Distributions.Deterministic", "class_numerics_1_1_distributions_1_1_deterministic.html", null ],
          [ "Numerics.Distributions.EmpiricalDistribution", "class_numerics_1_1_distributions_1_1_empirical_distribution.html", null ],
          [ "Numerics.Distributions.Exponential", "class_numerics_1_1_distributions_1_1_exponential.html", null ],
          [ "Numerics.Distributions.GammaDistribution", "class_numerics_1_1_distributions_1_1_gamma_distribution.html", null ],
          [ "Numerics.Distributions.GeneralizedBeta", "class_numerics_1_1_distributions_1_1_generalized_beta.html", null ],
          [ "Numerics.Distributions.GeneralizedExtremeValue", "class_numerics_1_1_distributions_1_1_generalized_extreme_value.html", null ],
          [ "Numerics.Distributions.GeneralizedLogistic", "class_numerics_1_1_distributions_1_1_generalized_logistic.html", null ],
          [ "Numerics.Distributions.GeneralizedNormal", "class_numerics_1_1_distributions_1_1_generalized_normal.html", null ],
          [ "Numerics.Distributions.GeneralizedPareto", "class_numerics_1_1_distributions_1_1_generalized_pareto.html", null ],
          [ "Numerics.Distributions.Geometric", "class_numerics_1_1_distributions_1_1_geometric.html", null ],
          [ "Numerics.Distributions.Gumbel", "class_numerics_1_1_distributions_1_1_gumbel.html", null ],
          [ "Numerics.Distributions.InverseChiSquared", "class_numerics_1_1_distributions_1_1_inverse_chi_squared.html", null ],
          [ "Numerics.Distributions.InverseGamma", "class_numerics_1_1_distributions_1_1_inverse_gamma.html", null ],
          [ "Numerics.Distributions.KappaFour", "class_numerics_1_1_distributions_1_1_kappa_four.html", null ],
          [ "Numerics.Distributions.KernelDensity", "class_numerics_1_1_distributions_1_1_kernel_density.html", null ],
          [ "Numerics.Distributions.LnNormal", "class_numerics_1_1_distributions_1_1_ln_normal.html", null ],
          [ "Numerics.Distributions.LogNormal", "class_numerics_1_1_distributions_1_1_log_normal.html", null ],
          [ "Numerics.Distributions.LogPearsonTypeIII", "class_numerics_1_1_distributions_1_1_log_pearson_type_i_i_i.html", null ],
          [ "Numerics.Distributions.Logistic", "class_numerics_1_1_distributions_1_1_logistic.html", null ],
          [ "Numerics.Distributions.Mixture", "class_numerics_1_1_distributions_1_1_mixture.html", null ],
          [ "Numerics.Distributions.NoncentralT", "class_numerics_1_1_distributions_1_1_noncentral_t.html", null ],
          [ "Numerics.Distributions.Normal", "class_numerics_1_1_distributions_1_1_normal.html", null ],
          [ "Numerics.Distributions.Pareto", "class_numerics_1_1_distributions_1_1_pareto.html", null ],
          [ "Numerics.Distributions.PearsonTypeIII", "class_numerics_1_1_distributions_1_1_pearson_type_i_i_i.html", null ],
          [ "Numerics.Distributions.Pert", "class_numerics_1_1_distributions_1_1_pert.html", null ],
          [ "Numerics.Distributions.PertPercentile", "class_numerics_1_1_distributions_1_1_pert_percentile.html", null ],
          [ "Numerics.Distributions.PertPercentileZ", "class_numerics_1_1_distributions_1_1_pert_percentile_z.html", null ],
          [ "Numerics.Distributions.Poisson", "class_numerics_1_1_distributions_1_1_poisson.html", null ],
          [ "Numerics.Distributions.Rayleigh", "class_numerics_1_1_distributions_1_1_rayleigh.html", null ],
          [ "Numerics.Distributions.StudentT", "class_numerics_1_1_distributions_1_1_student_t.html", null ],
          [ "Numerics.Distributions.Triangular", "class_numerics_1_1_distributions_1_1_triangular.html", null ],
          [ "Numerics.Distributions.TruncatedNormal", "class_numerics_1_1_distributions_1_1_truncated_normal.html", null ],
          [ "Numerics.Distributions.Uniform", "class_numerics_1_1_distributions_1_1_uniform.html", null ],
          [ "Numerics.Distributions.UniformDiscrete", "class_numerics_1_1_distributions_1_1_uniform_discrete.html", null ],
          [ "Numerics.Distributions.Weibull", "class_numerics_1_1_distributions_1_1_weibull.html", null ]
        ] ]
      ] ]
    ] ],
    [ "Numerics.Distributions.IEstimation", "interface_numerics_1_1_distributions_1_1_i_estimation.html", [
      [ "Numerics.Distributions.CompetingRisks", "class_numerics_1_1_distributions_1_1_competing_risks.html", null ],
      [ "Numerics.Distributions.Deterministic", "class_numerics_1_1_distributions_1_1_deterministic.html", null ],
      [ "Numerics.Distributions.Exponential", "class_numerics_1_1_distributions_1_1_exponential.html", null ],
      [ "Numerics.Distributions.GammaDistribution", "class_numerics_1_1_distributions_1_1_gamma_distribution.html", null ],
      [ "Numerics.Distributions.GeneralizedExtremeValue", "class_numerics_1_1_distributions_1_1_generalized_extreme_value.html", null ],
      [ "Numerics.Distributions.GeneralizedLogistic", "class_numerics_1_1_distributions_1_1_generalized_logistic.html", null ],
      [ "Numerics.Distributions.GeneralizedNormal", "class_numerics_1_1_distributions_1_1_generalized_normal.html", null ],
      [ "Numerics.Distributions.GeneralizedPareto", "class_numerics_1_1_distributions_1_1_generalized_pareto.html", null ],
      [ "Numerics.Distributions.Gumbel", "class_numerics_1_1_distributions_1_1_gumbel.html", null ],
      [ "Numerics.Distributions.KappaFour", "class_numerics_1_1_distributions_1_1_kappa_four.html", null ],
      [ "Numerics.Distributions.LnNormal", "class_numerics_1_1_distributions_1_1_ln_normal.html", null ],
      [ "Numerics.Distributions.LogNormal", "class_numerics_1_1_distributions_1_1_log_normal.html", null ],
      [ "Numerics.Distributions.LogPearsonTypeIII", "class_numerics_1_1_distributions_1_1_log_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Logistic", "class_numerics_1_1_distributions_1_1_logistic.html", null ],
      [ "Numerics.Distributions.Mixture", "class_numerics_1_1_distributions_1_1_mixture.html", null ],
      [ "Numerics.Distributions.Normal", "class_numerics_1_1_distributions_1_1_normal.html", null ],
      [ "Numerics.Distributions.PearsonTypeIII", "class_numerics_1_1_distributions_1_1_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Pert", "class_numerics_1_1_distributions_1_1_pert.html", null ],
      [ "Numerics.Distributions.Rayleigh", "class_numerics_1_1_distributions_1_1_rayleigh.html", null ],
      [ "Numerics.Distributions.Triangular", "class_numerics_1_1_distributions_1_1_triangular.html", null ],
      [ "Numerics.Distributions.TruncatedNormal", "class_numerics_1_1_distributions_1_1_truncated_normal.html", null ],
      [ "Numerics.Distributions.Weibull", "class_numerics_1_1_distributions_1_1_weibull.html", null ]
    ] ],
    [ "Numerics.Distributions.ILinearMomentEstimation", "interface_numerics_1_1_distributions_1_1_i_linear_moment_estimation.html", [
      [ "Numerics.Distributions.Exponential", "class_numerics_1_1_distributions_1_1_exponential.html", null ],
      [ "Numerics.Distributions.GammaDistribution", "class_numerics_1_1_distributions_1_1_gamma_distribution.html", null ],
      [ "Numerics.Distributions.GeneralizedExtremeValue", "class_numerics_1_1_distributions_1_1_generalized_extreme_value.html", null ],
      [ "Numerics.Distributions.GeneralizedLogistic", "class_numerics_1_1_distributions_1_1_generalized_logistic.html", null ],
      [ "Numerics.Distributions.GeneralizedNormal", "class_numerics_1_1_distributions_1_1_generalized_normal.html", null ],
      [ "Numerics.Distributions.GeneralizedPareto", "class_numerics_1_1_distributions_1_1_generalized_pareto.html", null ],
      [ "Numerics.Distributions.Gumbel", "class_numerics_1_1_distributions_1_1_gumbel.html", null ],
      [ "Numerics.Distributions.KappaFour", "class_numerics_1_1_distributions_1_1_kappa_four.html", null ],
      [ "Numerics.Distributions.LnNormal", "class_numerics_1_1_distributions_1_1_ln_normal.html", null ],
      [ "Numerics.Distributions.LogNormal", "class_numerics_1_1_distributions_1_1_log_normal.html", null ],
      [ "Numerics.Distributions.LogPearsonTypeIII", "class_numerics_1_1_distributions_1_1_log_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Normal", "class_numerics_1_1_distributions_1_1_normal.html", null ],
      [ "Numerics.Distributions.PearsonTypeIII", "class_numerics_1_1_distributions_1_1_pearson_type_i_i_i.html", null ]
    ] ],
    [ "IList", null, [
      [ "Numerics.Data.OrderedPairedData", "class_numerics_1_1_data_1_1_ordered_paired_data.html", null ],
      [ "Numerics.Data.Series< TIndex, TValue >", "class_numerics_1_1_data_1_1_series.html", null ],
      [ "Numerics.Data.Series< TIndex, TValue >", "class_numerics_1_1_data_1_1_series.html", null ],
      [ "Numerics.Data.UncertainOrderedPairedData", "class_numerics_1_1_data_1_1_uncertain_ordered_paired_data.html", null ]
    ] ],
    [ "Numerics.Distributions.IMaximumLikelihoodEstimation", "interface_numerics_1_1_distributions_1_1_i_maximum_likelihood_estimation.html", [
      [ "Numerics.Distributions.CompetingRisks", "class_numerics_1_1_distributions_1_1_competing_risks.html", null ],
      [ "Numerics.Distributions.Exponential", "class_numerics_1_1_distributions_1_1_exponential.html", null ],
      [ "Numerics.Distributions.GammaDistribution", "class_numerics_1_1_distributions_1_1_gamma_distribution.html", null ],
      [ "Numerics.Distributions.GeneralizedExtremeValue", "class_numerics_1_1_distributions_1_1_generalized_extreme_value.html", null ],
      [ "Numerics.Distributions.GeneralizedLogistic", "class_numerics_1_1_distributions_1_1_generalized_logistic.html", null ],
      [ "Numerics.Distributions.GeneralizedNormal", "class_numerics_1_1_distributions_1_1_generalized_normal.html", null ],
      [ "Numerics.Distributions.GeneralizedPareto", "class_numerics_1_1_distributions_1_1_generalized_pareto.html", null ],
      [ "Numerics.Distributions.Gumbel", "class_numerics_1_1_distributions_1_1_gumbel.html", null ],
      [ "Numerics.Distributions.KappaFour", "class_numerics_1_1_distributions_1_1_kappa_four.html", null ],
      [ "Numerics.Distributions.LnNormal", "class_numerics_1_1_distributions_1_1_ln_normal.html", null ],
      [ "Numerics.Distributions.LogNormal", "class_numerics_1_1_distributions_1_1_log_normal.html", null ],
      [ "Numerics.Distributions.LogPearsonTypeIII", "class_numerics_1_1_distributions_1_1_log_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Logistic", "class_numerics_1_1_distributions_1_1_logistic.html", null ],
      [ "Numerics.Distributions.Mixture", "class_numerics_1_1_distributions_1_1_mixture.html", null ],
      [ "Numerics.Distributions.Normal", "class_numerics_1_1_distributions_1_1_normal.html", null ],
      [ "Numerics.Distributions.PearsonTypeIII", "class_numerics_1_1_distributions_1_1_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Pert", "class_numerics_1_1_distributions_1_1_pert.html", null ],
      [ "Numerics.Distributions.Triangular", "class_numerics_1_1_distributions_1_1_triangular.html", null ],
      [ "Numerics.Distributions.Weibull", "class_numerics_1_1_distributions_1_1_weibull.html", null ]
    ] ],
    [ "Numerics.Distributions.IMomentEstimation", "interface_numerics_1_1_distributions_1_1_i_moment_estimation.html", [
      [ "Numerics.Distributions.Exponential", "class_numerics_1_1_distributions_1_1_exponential.html", null ],
      [ "Numerics.Distributions.GammaDistribution", "class_numerics_1_1_distributions_1_1_gamma_distribution.html", null ],
      [ "Numerics.Distributions.Gumbel", "class_numerics_1_1_distributions_1_1_gumbel.html", null ],
      [ "Numerics.Distributions.LnNormal", "class_numerics_1_1_distributions_1_1_ln_normal.html", null ],
      [ "Numerics.Distributions.LogNormal", "class_numerics_1_1_distributions_1_1_log_normal.html", null ],
      [ "Numerics.Distributions.LogPearsonTypeIII", "class_numerics_1_1_distributions_1_1_log_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Logistic", "class_numerics_1_1_distributions_1_1_logistic.html", null ],
      [ "Numerics.Distributions.Normal", "class_numerics_1_1_distributions_1_1_normal.html", null ],
      [ "Numerics.Distributions.PearsonTypeIII", "class_numerics_1_1_distributions_1_1_pearson_type_i_i_i.html", null ]
    ] ],
    [ "INotifyCollectionChanged", null, [
      [ "Numerics.Data.OrderedPairedData", "class_numerics_1_1_data_1_1_ordered_paired_data.html", null ],
      [ "Numerics.Data.Series< TIndex, TValue >", "class_numerics_1_1_data_1_1_series.html", null ],
      [ "Numerics.Data.UncertainOrderedPairedData", "class_numerics_1_1_data_1_1_uncertain_ordered_paired_data.html", null ]
    ] ],
    [ "INotifyPropertyChanged", null, [
      [ "Numerics.Data.SeriesOrdinate< TIndex, TValue >", "class_numerics_1_1_data_1_1_series_ordinate.html", null ]
    ] ],
    [ "Numerics.Mathematics.Integration.Integration", "class_numerics_1_1_mathematics_1_1_integration_1_1_integration.html", null ],
    [ "Numerics.Mathematics.Integration.Integrator", "class_numerics_1_1_mathematics_1_1_integration_1_1_integrator.html", [
      [ "Numerics.Mathematics.Integration.AdaptiveGaussLobatto", "class_numerics_1_1_mathematics_1_1_integration_1_1_adaptive_gauss_lobatto.html", null ],
      [ "Numerics.Mathematics.Integration.AdaptiveSimpsonsRule", "class_numerics_1_1_mathematics_1_1_integration_1_1_adaptive_simpsons_rule.html", null ],
      [ "Numerics.Mathematics.Integration.Miser", "class_numerics_1_1_mathematics_1_1_integration_1_1_miser.html", null ],
      [ "Numerics.Mathematics.Integration.MonteCarloIntegration", "class_numerics_1_1_mathematics_1_1_integration_1_1_monte_carlo_integration.html", null ],
      [ "Numerics.Mathematics.Integration.SimpsonsRule", "class_numerics_1_1_mathematics_1_1_integration_1_1_simpsons_rule.html", null ],
      [ "Numerics.Mathematics.Integration.TrapezoidalRule", "class_numerics_1_1_mathematics_1_1_integration_1_1_trapezoidal_rule.html", null ],
      [ "Numerics.Mathematics.Integration.Vegas", "class_numerics_1_1_mathematics_1_1_integration_1_1_vegas.html", null ]
    ] ],
    [ "Numerics.Data.Interpolater", "class_numerics_1_1_data_1_1_interpolater.html", [
      [ "Numerics.Data.CubicSpline", "class_numerics_1_1_data_1_1_cubic_spline.html", null ],
      [ "Numerics.Data.Linear", "class_numerics_1_1_data_1_1_linear.html", null ],
      [ "Numerics.Data.Polynomial", "class_numerics_1_1_data_1_1_polynomial.html", null ]
    ] ],
    [ "Numerics.Distributions.IStandardError", "interface_numerics_1_1_distributions_1_1_i_standard_error.html", [
      [ "Numerics.Distributions.Exponential", "class_numerics_1_1_distributions_1_1_exponential.html", null ],
      [ "Numerics.Distributions.GammaDistribution", "class_numerics_1_1_distributions_1_1_gamma_distribution.html", null ],
      [ "Numerics.Distributions.GeneralizedExtremeValue", "class_numerics_1_1_distributions_1_1_generalized_extreme_value.html", null ],
      [ "Numerics.Distributions.GeneralizedLogistic", "class_numerics_1_1_distributions_1_1_generalized_logistic.html", null ],
      [ "Numerics.Distributions.GeneralizedNormal", "class_numerics_1_1_distributions_1_1_generalized_normal.html", null ],
      [ "Numerics.Distributions.GeneralizedPareto", "class_numerics_1_1_distributions_1_1_generalized_pareto.html", null ],
      [ "Numerics.Distributions.Gumbel", "class_numerics_1_1_distributions_1_1_gumbel.html", null ],
      [ "Numerics.Distributions.KappaFour", "class_numerics_1_1_distributions_1_1_kappa_four.html", null ],
      [ "Numerics.Distributions.LnNormal", "class_numerics_1_1_distributions_1_1_ln_normal.html", null ],
      [ "Numerics.Distributions.LogNormal", "class_numerics_1_1_distributions_1_1_log_normal.html", null ],
      [ "Numerics.Distributions.LogPearsonTypeIII", "class_numerics_1_1_distributions_1_1_log_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Logistic", "class_numerics_1_1_distributions_1_1_logistic.html", null ],
      [ "Numerics.Distributions.Normal", "class_numerics_1_1_distributions_1_1_normal.html", null ],
      [ "Numerics.Distributions.PearsonTypeIII", "class_numerics_1_1_distributions_1_1_pearson_type_i_i_i.html", null ],
      [ "Numerics.Distributions.Weibull", "class_numerics_1_1_distributions_1_1_weibull.html", null ]
    ] ],
    [ "Numerics.Functions.IUnivariateFunction", "interface_numerics_1_1_functions_1_1_i_univariate_function.html", [
      [ "Numerics.Functions.LinearFunction", "class_numerics_1_1_functions_1_1_linear_function.html", null ],
      [ "Numerics.Functions.PowerFunction", "class_numerics_1_1_functions_1_1_power_function.html", null ],
      [ "Numerics.Functions.TabularFunction", "class_numerics_1_1_functions_1_1_tabular_function.html", null ]
    ] ],
    [ "Numerics.MachineLearning.JenksCluster", "class_numerics_1_1_machine_learning_1_1_jenks_cluster.html", null ],
    [ "Numerics.MachineLearning.JenksNaturalBreaks", "class_numerics_1_1_machine_learning_1_1_jenks_natural_breaks.html", null ],
    [ "Numerics.MachineLearning.KMeans", "class_numerics_1_1_machine_learning_1_1_k_means.html", null ],
    [ "Numerics.MachineLearning.KNearestNeighbors", "class_numerics_1_1_machine_learning_1_1_k_nearest_neighbors.html", null ],
    [ "Numerics.Sampling.LatinHypercube", "class_numerics_1_1_sampling_1_1_latin_hypercube.html", null ],
    [ "Numerics.Data.LinearRegression", "class_numerics_1_1_data_1_1_linear_regression.html", null ],
    [ "Numerics.Data.LineSimplification", "class_numerics_1_1_data_1_1_line_simplification.html", null ],
    [ "Numerics.Mathematics.LinearAlgebra.LUDecomposition", "class_numerics_1_1_mathematics_1_1_linear_algebra_1_1_l_u_decomposition.html", null ],
    [ "Numerics.Mathematics.LinearAlgebra.Matrix", "class_numerics_1_1_mathematics_1_1_linear_algebra_1_1_matrix.html", null ],
    [ "Numerics.Sampling.MCMC.MCMCDiagnostics", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_m_c_m_c_diagnostics.html", null ],
    [ "Numerics.Sampling.MCMC.MCMCResults", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_m_c_m_c_results.html", null ],
    [ "Numerics.Sampling.MCMC.MCMCSampler", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_m_c_m_c_sampler.html", [
      [ "Numerics.Sampling.MCMC.ARWMH", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_a_r_w_m_h.html", null ],
      [ "Numerics.Sampling.MCMC.DEMCz", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_d_e_m_cz.html", null ],
      [ "Numerics.Sampling.MCMC.DEMCzs", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_d_e_m_czs.html", null ],
      [ "Numerics.Sampling.MCMC.Gibbs", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_gibbs.html", null ],
      [ "Numerics.Sampling.MCMC.HMC", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_h_m_c.html", null ],
      [ "Numerics.Sampling.MCMC.RWMH", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_r_w_m_h.html", null ],
      [ "Numerics.Sampling.MCMC.SNIS", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_s_n_i_s.html", null ]
    ] ],
    [ "Numerics.Utilities.SafeProgressReporter.MessageContentStruct", "struct_numerics_1_1_utilities_1_1_safe_progress_reporter_1_1_message_content_struct.html", null ],
    [ "Numerics.Data.Statistics.MultipleGrubbsBeckTest", "class_numerics_1_1_data_1_1_statistics_1_1_multiple_grubbs_beck_test.html", null ],
    [ "Numerics.MachineLearning.NaiveBayes", "class_numerics_1_1_machine_learning_1_1_naive_bayes.html", null ],
    [ "Numerics.Mathematics.RootFinding.NewtonRaphson", "class_numerics_1_1_mathematics_1_1_root_finding_1_1_newton_raphson.html", null ],
    [ "Numerics.Mathematics.NumericalDerivative", "class_numerics_1_1_mathematics_1_1_numerical_derivative.html", null ],
    [ "Numerics.Mathematics.Optimization.Optimizer", "class_numerics_1_1_mathematics_1_1_optimization_1_1_optimizer.html", [
      [ "Numerics.Mathematics.Optimization.ADAM", "class_numerics_1_1_mathematics_1_1_optimization_1_1_a_d_a_m.html", null ],
      [ "Numerics.Mathematics.Optimization.AugmentedLagrange", "class_numerics_1_1_mathematics_1_1_optimization_1_1_augmented_lagrange.html", null ],
      [ "Numerics.Mathematics.Optimization.BFGS", "class_numerics_1_1_mathematics_1_1_optimization_1_1_b_f_g_s.html", null ],
      [ "Numerics.Mathematics.Optimization.BrentSearch", "class_numerics_1_1_mathematics_1_1_optimization_1_1_brent_search.html", null ],
      [ "Numerics.Mathematics.Optimization.DifferentialEvolution", "class_numerics_1_1_mathematics_1_1_optimization_1_1_differential_evolution.html", null ],
      [ "Numerics.Mathematics.Optimization.GoldenSection", "class_numerics_1_1_mathematics_1_1_optimization_1_1_golden_section.html", null ],
      [ "Numerics.Mathematics.Optimization.GradientDescent", "class_numerics_1_1_mathematics_1_1_optimization_1_1_gradient_descent.html", null ],
      [ "Numerics.Mathematics.Optimization.MLSL", "class_numerics_1_1_mathematics_1_1_optimization_1_1_m_l_s_l.html", null ],
      [ "Numerics.Mathematics.Optimization.MultiStart", "class_numerics_1_1_mathematics_1_1_optimization_1_1_multi_start.html", null ],
      [ "Numerics.Mathematics.Optimization.NelderMead", "class_numerics_1_1_mathematics_1_1_optimization_1_1_nelder_mead.html", null ],
      [ "Numerics.Mathematics.Optimization.ParticleSwarm", "class_numerics_1_1_mathematics_1_1_optimization_1_1_particle_swarm.html", null ],
      [ "Numerics.Mathematics.Optimization.Powell", "class_numerics_1_1_mathematics_1_1_optimization_1_1_powell.html", null ],
      [ "Numerics.Mathematics.Optimization.ShuffledComplexEvolution", "class_numerics_1_1_mathematics_1_1_optimization_1_1_shuffled_complex_evolution.html", null ],
      [ "Numerics.Mathematics.Optimization.SimulatedAnnealing", "class_numerics_1_1_mathematics_1_1_optimization_1_1_simulated_annealing.html", null ]
    ] ],
    [ "Numerics.Data.Ordinate", "struct_numerics_1_1_data_1_1_ordinate.html", null ],
    [ "Numerics.Sampling.MCMC.ParameterResults", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_parameter_results.html", null ],
    [ "Numerics.Mathematics.Optimization.ParameterSet", "struct_numerics_1_1_mathematics_1_1_optimization_1_1_parameter_set.html", null ],
    [ "Numerics.Sampling.MCMC.ParameterStatistics", "class_numerics_1_1_sampling_1_1_m_c_m_c_1_1_parameter_statistics.html", null ],
    [ "Numerics.Data.Statistics.PlottingPositions", "class_numerics_1_1_data_1_1_statistics_1_1_plotting_positions.html", null ],
    [ "Numerics.Data.Statistics.Probability", "class_numerics_1_1_data_1_1_statistics_1_1_probability.html", null ],
    [ "Random", null, [
      [ "Numerics.Sampling.MersenneTwister", "class_numerics_1_1_sampling_1_1_mersenne_twister.html", null ]
    ] ],
    [ "Numerics.MachineLearning.RandomForest", "class_numerics_1_1_machine_learning_1_1_random_forest.html", null ],
    [ "Numerics.Properties.Resources", "class_numerics_1_1_properties_1_1_resources.html", null ],
    [ "Numerics.Mathematics.ODESolvers.RungeKutta", "class_numerics_1_1_mathematics_1_1_o_d_e_solvers_1_1_runge_kutta.html", null ],
    [ "Numerics.Data.Statistics.RunningCovarianceMatrix", "class_numerics_1_1_data_1_1_statistics_1_1_running_covariance_matrix.html", null ],
    [ "Numerics.Data.Statistics.RunningStatistics", "class_numerics_1_1_data_1_1_statistics_1_1_running_statistics.html", null ],
    [ "Numerics.Utilities.SafeProgressReporter", "class_numerics_1_1_utilities_1_1_safe_progress_reporter.html", null ],
    [ "Numerics.Mathematics.Optimization.MLSL.SamplePoint", "class_numerics_1_1_mathematics_1_1_optimization_1_1_m_l_s_l_1_1_sample_point.html", null ],
    [ "Numerics.Data.Search", "class_numerics_1_1_data_1_1_search.html", null ],
    [ "Numerics.Mathematics.RootFinding.Secant", "class_numerics_1_1_mathematics_1_1_root_finding_1_1_secant.html", null ],
    [ "Numerics.Data.Series< DateTime, double >", "class_numerics_1_1_data_1_1_series.html", [
      [ "Numerics.Data.TimeSeries", "class_numerics_1_1_data_1_1_time_series.html", null ]
    ] ],
    [ "Numerics.Mathematics.LinearAlgebra.SingularValueDecomposition", "class_numerics_1_1_mathematics_1_1_linear_algebra_1_1_singular_value_decomposition.html", null ],
    [ "Numerics.Sampling.SobolSequence", "class_numerics_1_1_sampling_1_1_sobol_sequence.html", null ],
    [ "Numerics.Data.Statistics.Statistics", "class_numerics_1_1_data_1_1_statistics_1_1_statistics.html", null ],
    [ "Numerics.Sampling.StratificationOptions", "class_numerics_1_1_sampling_1_1_stratification_options.html", null ],
    [ "Numerics.Sampling.Stratify", "class_numerics_1_1_sampling_1_1_stratify.html", null ],
    [ "Numerics.Data.TimeSeriesDownload", "class_numerics_1_1_data_1_1_time_series_download.html", null ],
    [ "Numerics.Tools", "class_numerics_1_1_tools.html", null ],
    [ "Numerics.Data.UncertainOrdinate", "struct_numerics_1_1_data_1_1_uncertain_ordinate.html", null ],
    [ "Numerics.Distributions.UncertaintyAnalysisResults", "class_numerics_1_1_distributions_1_1_uncertainty_analysis_results.html", null ],
    [ "Numerics.Distributions.UnivariateDistributionFactory", "class_numerics_1_1_distributions_1_1_univariate_distribution_factory.html", null ],
    [ "Numerics.Mathematics.LinearAlgebra.Vector", "class_numerics_1_1_mathematics_1_1_linear_algebra_1_1_vector.html", null ]
];